---
version: '3.1'
services:
  teamspeak:
    image: docker.io/library/teamspeak:3.13.7
    restart: always
    ports:
      - 9987:9987/udp
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: ${DB_HOST}
      TS3SERVER_DB_USER: ${DB_USER}
      TS3SERVER_DB_PASSWORD: ${DB_PASSWORD}
      TS3SERVER_DB_NAME: ${DB_NAME}
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    volumes:
      - ts_data:/var/ts3server/
    depends_on: 
      - db
  db:
    image: docker.io/library/mariadb:12.0.1-ubi9-rc
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql/
volumes:
  db_data:
  ts_data:
