services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.25.1
    ports:
      - 13378:80
    volumes:
      - ./audiobooks:/audiobooks
      - ./podcasts:/podcasts
      - ./config:/config
      - ./metadata:/metadata
    environment:
      - TZ=Europe/Berlin

  tunnel:
    image: docker.io/cloudflare/cloudflared:2025.7.0
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
