services:
  web:
    #build: ./frontend/
    image: ghcr.io/seanmorley15/adventurelog-frontend:v0.11.0
    container_name: adventurelog-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-8015}:3000"
    depends_on:
      - server
    env_file:
      - stack.env

  db:
    image: postgis/postgis:16-3.5
    container_name: adventurelog-db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      PGHOST: ${PGHOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  server:
    #build: ./backend/
    image: ghcr.io/seanmorley15/adventurelog-backend:v0.11.0
    container_name: adventurelog-backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-8016}:80"
    depends_on:
      - db
    volumes:
      - adventurelog_media:/code/media/
    env_file:
      - stack.env

volumes:
  postgres_data:
  adventurelog_media:
