version: '3'

services:
  vikunja:
    image: docker.io/vikunja/vikunja:0.24.6
    environment:
      VIKUNJA_SERVICE_PUBLICURL: ${PUBLIC_URL}
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_HOST: ${MYSQL_HOST}
      VIKUNJA_DATABASE_USER: ${MYSQL_USER}
      VIKUNJA_DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      VIKUNJA_DATABASE_DATABASE: ${MYSQL_DATABASE}
      VIKUNJA_SERVICE_JWTSECRET: ${JWT_SECRET}
      VIKUNJA_CORS_ENABLE: true
    ports:
      - 3456:3456
    volumes:
      - files:/app/vikunja/files
    # depends_on:
    #   vikunja-mysql:
    #     condition: service_healthy
    #   vikunja-redis:
    #     condition: service_healthy
    restart: always

  tunnel:
    image: docker.io/cloudflare/cloudflared:2025.8.1
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "128M"

volumes:
  files:
  redis:
