---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: teamspeak
  name: teamspeak
  namespace: teamspeak
spec:
  externalTrafficPolicy: Local
  ports:
    - name: voice
      port: 9987
      protocol: UDP
      targetPort: 9987
      nodePort: 9987
    - name: filetransfer
      port: 30033
      targetPort: 30033
      nodePort: 30033
    - name: webquery
      port: 10080
      targetPort: 10080
  selector:
    io.kompose.service: teamspeak
  type: NodePort
