---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: teamspeak
    app.kubernetes.io/instance: teamspeak
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: teamspeak
  name: teamspeak-metrics
  namespace: teamspeak
spec:
  ports:
    - name: metrics
      port: 9187
      protocol: TCP
      targetPort: 9187
  selector:
    app.kubernetes.io/name: teamspeak
    app.kubernetes.io/instance: teamspeak
    app.kubernetes.io/component: server
  type: ClusterIP
