---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: teamspeak
    app.kubernetes.io/instance: teamspeak
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: teamspeak
  name: teamspeak
  namespace: teamspeak
spec:
  externalTrafficPolicy: Local
  ports:
    - name: voice
      port: 9987
      protocol: UDP
      targetPort: 9987
      nodePort: 9987
    - name: filetransfer
      port: 30033
      targetPort: 30033
      nodePort: 30033
    - name: webquery
      port: 10080
      targetPort: 10080
  selector:
    app.kubernetes.io/name: teamspeak
    app.kubernetes.io/instance: teamspeak
    app.kubernetes.io/component: server
  type: NodePort
