---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: mumble
  name: mumble
  namespace: mumble
spec:
  externalTrafficPolicy: Local
  ports:
    - name: voice
      port: 64738
      protocol: UDP
      targetPort: 64738
      nodePort: 64738
    - name: voice-tcp
      port: 64738
      protocol: TCP
      targetPort: 64738
      nodePort: 64738
  selector:
    io.kompose.service: mumble
  type: NodePort
