apiVersion: v1
kind: Secret
metadata:
  name: mysql-backup-creds
type: Opaque
stringData:
  databases: "kubernetes,vikunja"
  host: "10.0.0.170"
  username: "adminmann123"
  password: "zme4wzyoQKZ9pwg5gqc!"
  token: 
  chat-id: 
