version: "3"

services:
  server:
    image: docker.io/gitea/gitea:1.23.5
    restart: always
    container_name: gitea
    environment:
      - USER_UID=${GITTEA_UID}
      - USER_GID=${GITTEA_GID}
      - GITEA__database__DB_TYPE=${DB_TYPE}
      - GITEA__database__HOST=${DB_HOST}
      - GITEA__database__NAME=${DB_NAME}
      - GITEA__database__USER=${DB_USER}
      - GITEA__database__PASSWD=${DB_PASS}
      - GITEA__service__DISABLE_REGISTRATION=true
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3333:22"
    #   - "3000:3000"

  revproxy:
    #image: docker.io/library/caddy:2.9.1-alpine
    image: localhost/gittea_revproxy:latest
    build: 
      context: /home/ubuntu/workspace/gittea
      dockerfile: caddy-dockerfile
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data # Persistent certificate storage
      - ./geolite2-country.mmdb:/etc/maxmind/geolite2-country.mmdb:ro

volumes:
  caddy_data:
