services:
  app:
    image: docker.io/monica:4.1.2
    depends_on:
      - db
    ports:
      - 7777:80
    environment:
      - APP_KEY=${APP_KEY} 
      - DB_HOST=db
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - data:/var/www/html/storage
    restart: always

  db:
    image: docker.io/mariadb:11.8.3-ubi9
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    restart: always

volumes:
  data:
    name: data
  mysql:
    name: mysql
